<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?= /* @noEscape */ $_menuHtml?>
        <?= $block->getChildHtml() ?>
    </ul>
</nav>
<script>
require(['jquery', 'jquerySticky'], function($){
    $(document).ready(function() {
        if ($(window).width() > 767) {
            $(".nav-sections").sticky({
                topSpacing: 0,
                zIndex: 10
            });
        }
    });
    $(window).resize(function() {
        if ($(window).width() > 767) {
            $(".nav-sections").sticky({
                topSpacing: 0,
                zIndex: 10
            });
        } else {
            $(".nav-sections").unstick();
        }
    });
});
</script>